name: hello-world
on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

  deploy-to-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: my-step
        run: echo "Deploying to dev environment..."

  deploy-to-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: my-step
        run: echo "Deploying to prod environment..."
