name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

  deploytodev:
      runs-on: ubuntu-latest
      environment-name: dev
    steps:
      - name: my-step
        run: echo "Hello World!"
  deploytoprod:
   runs-on: ubuntu-latest
   environment-name: prod
    steps:
      - name: my-step
        run: echo "Hello World!"
    

